In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [6]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[5.88361544e-01 5.93085862e-01 2.41711931e-01 ... 5.90334000e-01
  7.70729860e-01 2.69087986e-01]
 [5.13227039e-01 7.73533347e-01 1.28360643e-02 ... 5.63277656e-01
  6.01576076e-01 7.61690138e-01]
 [1.67335900e-01 8.03020554e-01 6.32696584e-01 ... 4.66405126e-01
  7.60603141e-01 4.00382379e-01]
 ...
 [5.39717929e-01 7.99344687e-01 6.42186220e-01 ... 5.03815882e-01
  6.34741819e-01 6.45818493e-01]
 [1.15928331e-01 1.23885832e-01 6.91281113e-01 ... 2.88792763e-01
  8.95594039e-01 2.99072912e-04]
 [7.02592418e-01 9.12588691e-02 8.37955658e-01 ... 3.68457780e-01
  9.07054378e-01 2.87169031e-01]]
[[0.45885519 0.75315945 0.31220722 ... 0.15000891 0.15070304 0.62623884]
 [0.56066814 0.73191789 0.42943275 ... 0.35305277 0.62196569 0.82988802]
 [0.33461656 0.21901428 0.43273336 ... 0.08351098 0.06277209 0.57029491]
 ...
 [0.98848583 0.34968989 0.4224977  ... 0.15695634 0.22714899 0.58089317]
 [0.3126039  0.5171

Без использования numpy

In [3]:
def mult(a, b):
    result = None
    rows_a, cols_a = len(a), len(a[0])
    rows_b, cols_b = len(b), len(b[0])
    result = [[0 for _ in range(cols_b)] for _ in range(rows_a)]
    for i in range(rows_a):
        for j in range(cols_b):
            for k in range(cols_a):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [4]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [7]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 711 ms, sys: 0 ns, total: 711 ms
Wall time: 718 ms


In [8]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 815 µs, sys: 4.94 ms, total: 5.75 ms
Wall time: 10.5 ms


In [9]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5418777365994174e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [10]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.6005792  0.2064836  0.38033791] [0.55199995 0.26037077 0.91868571]


In [11]:
def scalar_product(a,b):
    s = sum(ai * bi for ai, bi in zip(a, b))
    return s

In [12]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [13]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 29 µs, sys: 6 µs, total: 35 µs
Wall time: 38.9 µs
CPU times: user 0 ns, sys: 661 µs, total: 661 µs
Wall time: 2.64 ms


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы NumPy более эффективны благодаря оптимизированным векторизованным операциям с массивами, эффективному хранению в памяти.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [14]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = None
  diagonal_elements = np.diagonal(a)
  diagonal_elements = diagonal_elements[diagonal_elements % 2 == 0]
  res = np.sum(diagonal_elements)
  return res

In [15]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[7, 7, 1, 8, 7],
       [1, 9, 6, 1, 5],
       [3, 8, 3, 6, 7],
       [4, 6, 4, 4, 7],
       [7, 4, 5, 2, 8]])

In [16]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 137 µs, sys: 20 µs, total: 157 µs
Wall time: 163 µs


12

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [19]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = None
    A = np.array(A)
    cumsum_array = np.cumsum(A, axis=1)
    indices = np.arange(1, A.shape[1] + 1)
    result = cumsum_array / indices[:, np.newaxis]
    return result

In [20]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[3.64356418e-01 1.55730810e-01 3.34458517e-01 1.46215251e-01
 4.13079149e-01 8.70525129e-01 1.84368563e-02 2.68926976e-01
 3.80754368e-01 3.86973271e-01 5.60598451e-01 2.68804121e-01
 6.01163682e-01 8.68442519e-01 5.59467454e-02 8.26528060e-01
 1.32460477e-01 4.70514022e-01 7.98132896e-01 7.81346789e-01
 1.80806563e-01 2.44894697e-01 7.96785869e-01 1.85368806e-01
 6.53851905e-01 6.22779681e-02 6.80111368e-01 3.13944290e-01
 3.20874386e-02 8.11997313e-01 2.21545298e-01 7.52413863e-01
 2.90952979e-01 6.30457622e-01 7.24213487e-01 3.70336933e-01
 1.26766210e-02 8.91622639e-01 1.85244779e-01 7.82815068e-02
 3.12355605e-01 3.93492279e-01 1.29935840e-02 2.53397441e-01
 4.92672321e-01 6.38902713e-01 8.86404471e-01 5.76675039e-02
 5.28058667e-01 9.62841625e-01 5.32400579e-01 7.75368718e-01
 2.87419967e-01 6.64595127e-01 5.98702119e-01 4.57302653e-01
 6.43162118e-01 3.24256338e-01 2.11239772e-01 3.45291251e-01
 7.89056755e-01 1.97637392e-01 6.91789585e-02 4.50603511e-01
 7.19192862e-01 6.648992

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [21]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    result = None
    if len(a) == 0:
        return np.array([]), np.array([])
    unique_elements, counts = [a[0]], [1]
    for i in range(1, len(a)):
        if a[i] == a[i - 1]:
            counts[-1] += 1
        else:
            unique_elements.append(a[i])
            counts.append(1)
    result = np.array(unique_elements), np.array(counts)
    return result

In [22]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 45 µs, sys: 0 ns, total: 45 µs
Wall time: 50.5 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [23]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    result = None
    result = X.copy()
    result[1::2] = a
    result[0::2] **= 3
    result = result[::-1]
    result = np.concatenate((X, result))
    return result

In [24]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 193 µs, sys: 28 µs, total: 221 µs
Wall time: 1.26 ms
